version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:80"

  web_test:
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    command: vendor/bin/phpunit

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"

volumes:
  mysqldata: